[package]
name = "judash399/innercomponents"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"

repository = "https://github.com/Judash399/InnerComponents"

realm = "shared"
license = "MIT"
description = "A modern, simple component library for Fusion designed to feel part of Roblox Studio."

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
fusion = "elttob/fusion@0.3.0"
lucide-icons = "latte-soft/lucide-icons@0.1.3"